apps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("profile/<int:pk>/", views.Profile.as_view(), name="profile"),
    path("login/", views.LogIn.as_view(), name="login"),
    path("logout/", views.LogOut.as_view(), name="logout"),
    path("reset_password/", views.ResetPassword.as_view(), name="reset_password"),
    path(
        "reset_password_done/",
        views.ResetPasswordDone.as_view(),
        name="reset_password_done",
    ),
    path(
        "reset_password_complete/",
        views.ResetPasswordComplete.as_view(),
        name="reset_password_complete",
    ),
    path(
        "reset_password_confirm/$<uidb64>/<token>/",
        views.ResetPasswordConfirm.as_view(),
        name="reset_password_confirm",
    ),
]

yalantis_django/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
from . import views
from .settings import DEBUG
import debug_toolbar


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("about-us/", views.about_us, name="about_us"),
    path("authors/", views.authors, name="authors"),
    path("contacts/", views.contacts, name="contacts"),
    path("accounts/", include("apps.accounts.urls", namespace="accounts")),
    path("api/v1/dialogs/", include("apps.dialogs.urls", namespace="dialogs")),
    path("api/v1/super-login/", obtain_jwt_token, name="super_login"),
]

if DEBUG:
    urlpatterns.insert(0, path("__debug__/", include(debug_toolbar.urls)))

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import UserManager


class User(AbstractUser):
    email = models.EmailField(verbose_name="email", max_length=254, unique=True)
    phone = models.CharField(
        verbose_name="mobile phone", max_length=17, blank=True, null=True
    )
    password_expire_at = models.DateTimeField(
        verbose_name="expired at", null=True, blank=True
    )
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]
    objects = UserManager()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    PasswordResetForm,
    SetPasswordForm,
)
from .models import User


class CreationForm(UserCreationForm):
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Enter your password"}
        ),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Confirm your password"}
        ),
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
        )
        widgets = {
            "first_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter your name"}
            ),
            "last_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter your  last name"}
            ),
            "username": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter your username"}
            ),
            "email": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter correct email"}
            ),
        }
        help_texts = {
            "username": None,
            "email": None,
        }


class UpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "phone",
        )
        widgets = {
            "first_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter your name"}
            ),
            "last_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter your  last name"}
            ),
            "username": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter your username"}
            ),
            "email": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter correct email"}
            ),
            "phone": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter your  mobile phone",
                }
            ),
        }
        help_texts = {
            "username": None,
            "email": None,
        }


class LogInForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter your username or email",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Enter valid password"}
        )
    )

    def __init__(self, *args, **kwargs):
        super(LogInForm, self).__init__(*args, **kwargs)


class ResetPasswordForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter your email",
            }
        ),
    )


class PasswordSetForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter new password",
            }
        ),
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Confirm new password",
            }
        ),
    )

apps/accounts/views.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from .forms import (
    CreationForm,
    LogInForm,
    UpdateForm,
    ResetPasswordForm,
    PasswordSetForm,
)


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"


class LogIn(LoginView):
    form_class = LogInForm
    template_name = "accounts/login.html"

    def get_success_url(self):
        return reverse("index")


class LogOut(LogoutView):
    template_name = "accounts/logout.html"


class Profile(UpdateView):
    context_object_name = "variable_used_in `profile.html`"
    form_class = UpdateForm
    success_url = reverse_lazy("index")
    template_name = "accounts/profile.html"

    def get_object(self, queryset=None):
        return self.request.user


class ResetPassword(PasswordResetView):
    form_class = ResetPasswordForm
    success_url = reverse_lazy("accounts:reset_password_done")
    template_name = "accounts/reset_password.html"
    email_template_name = "accounts/reset_password_email.html"


class ResetPasswordDone(PasswordResetDoneView):
    template_name = "accounts/reset_password_done.html"


class ResetPasswordConfirm(PasswordResetConfirmView):
    form_class = PasswordSetForm
    success_url = reverse_lazy("accounts:reset_password_complete")
    template_name = "accounts/reset_password_confirm.html"


class ResetPasswordComplete(PasswordResetCompleteView):
    template_name = "accounts/reset_password_complete.html"

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}<title>Log In</title>{% endblock %}

{% block content %}

<h2>Log In</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Log In</button>
</form>
<hr>
<li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
<li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>

{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}<title>Log Out</title>{% endblock %}

{% block content %}
<h2>Logged out! Have a nice day!</h2>
<hr>
<li><a href="{% url 'accounts:login' %}">Log In again</a></li>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}<title>Account {{ user.get_username }}</title>{% endblock %}

{% block content %}
<h2>Profile: {{ user.get_username }}</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
  <button onclick="window.history.back();" type="button">Go back</button>
</form>
{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block title %}<title>Reset Password</title>{% endblock %}

{% block content %}
<h2>Reset password</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Reset Password</button>
  <button onclick="window.history.back();" type="button">Go back</button>
</form>
<hr>
{% endblock %}

templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block title %}<title>Reset Password</title>{% endblock %}

{% block content %}
<h2>Reset Password</h2>
<p>Password has been changed!</p>
<hr>
<li><a href="{% url 'accounts:login' %}">Log In</a></li>
{% endblock %}

templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block title %}<title>Reset Password</title>{% endblock %}

{% block content %}
<h2>Reset password</h2>
    {% if validlink %}
        <p>Please enter (and confirm) your new password.</p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Reset Password</button>
        </form>
    {% else %}
        <h1>Password reset failed</h1>
        <p>The password reset link was invalid, possibly because it has already been used.</p>
        <p>Please request a new password reset.</p>
    {% endif %}
<hr>
{% endblock %}

templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block title %}<title>Reset Password</title>{% endblock %}

{% block content %}
<h2>Reset password</h2>
<p>We've emailed you instructions for setting your password.</p>
<p>If they haven't arrived in a few minutes, check your spam folder.</p>
<hr>
{% endblock %}

templates/accounts/reset_password_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:reset_password_confirm' uidb64=uid token=token %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}<title>Sign Up</title>{% endblock %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Get Started!</button>
  <button onclick="window.history.back();" type="button">Go back</button>
</form>
{% endblock %}