apps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("profile/<int:pk>/", views.Profile.as_view(), name="profile"),
    path("login/", views.LogIn.as_view(), name="login"),
    path("logout/", views.LogOut.as_view(), name="logout"),
    path("reset_password/", views.ResetPassword.as_view(), name="reset_password"),
    path(
        "reset_password_done/",
        views.ResetPasswordDone.as_view(),
        name="reset_password_done",
    ),
    path(
        "reset_password_complete/",
        views.ResetPasswordComplete.as_view(),
        name="reset_password_complete",
    ),
    path(
        "reset_password_confirm/$<uidb64>/<token>/",
        views.ResetPasswordConfirm.as_view(),
        name="reset_password_confirm",
    ),
]

yalantis_django/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
from . import views
from .settings import DEBUG
import debug_toolbar


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("about-us/", views.about_us, name="about_us"),
    path("authors/", views.authors, name="authors"),
    path("contacts/", views.contacts, name="contacts"),
    path("accounts/", include("apps.accounts.urls", namespace="accounts")),
    path("api/v1/dialogs/", include("apps.dialogs.urls", namespace="dialogs")),
    path("api/v1/super-login/", obtain_jwt_token, name="super_login"),
]

if DEBUG:
    urlpatterns.insert(0, path("__debug__/", include(debug_toolbar.urls)))

templates/about_us.html
{% extends "base.html" %}

{% block title %}<title>About us</title>{% endblock %}

{% block content %}
<h1>Yalantis Django</h1>
<hr>
<h2>About us</h2>
{% endblock %}

templates/authors.html
{% extends "base.html" %}

{% block title %}<title>Authors</title>{% endblock %}

{% block content %}
<h1>Yalantis Django</h1>
<hr>
<h2>Authors</h2>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <hr>
          <li><a href="{% url 'index' %}">Home</a></li><hr>
          <li><a href="{% url 'about_us' %}">About us</a></li><hr>
          <li><a href="{% url 'contacts' %}">Contacts</a></li><hr>
          <li><a href="{% url 'authors' %}">Authors</a></li><hr>
          {% if user.is_authenticated %}
            <li>User: <a href="{% url 'accounts:profile' user.pk %}">{{ user.get_username }}</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
          {% endif %}
        </ul>
      {% endblock %}
      </div>
      <div class="col-sm-10 ">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

templates/contacts.html
{% extends "base.html" %}

{% block title %}<title>Contacts</title>{% endblock %}

{% block content %}
<h1>Yalantis Django</h1>
<hr>
<h2>Contacts</h2>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}<title>Home</title>{% endblock %}

{% block content %}
<h1>Yalantis Django</h1>
<hr>
<h2>Dynamic content</h2>
{% endblock %}